services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - shunbun-opensearch:/usr/share/opensearch/data
      # TODO: logs
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - shunbun-app
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - shunbun-app
  mysql:
    image: mysql:8
    container_name: mysql-server
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - shunbun-mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d/:/docker-entrypoint-initdb.d/
volumes:
  shunbun-mysql:
  shunbun-opensearch:

networks:
  shunbun-app:
